name: release-master

on:
  push:
    branches: ["master"]

jobs:
  subtrace-binary:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        set -e

        version=$(printf "b%03d" "$(git log --oneline | wc -l)")
        echo "version=${version}"

        for arch in amd64 arm64; do
          echo "arch=${arch}"
          GOARCH=${arch} time make subtrace
          mv subtrace subtrace-${version}-linux-${arch}
        done

        echo "metadata:"
        file subtrace-*
        sha256sum subtrace-*

        echo "creating releasing"
        time curl -sL "https://api.github.com/repos/subtrace/subtrace/releases" \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"tag_name":"'${version}'","target_commitish":"master","name":"'${version}'"}' \
          | jq -r '.id' \
          | read release_id
        echo "release_id=${release_id}"

        for file in subtrace-*; do
          echo "uploading ${file}"
          time curl -sL "https://api.github.com/repos/subtrace/subtrace/releases/${release_id}/assets?name=${file}" \
              -H "Content-Type: application/octet-stream" \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              --data-binary "@${file}"
        done

  worker-docker:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        set -e

        version=$(printf "b%03d" "$(git log --oneline | wc -l)")
        echo "version=${version}"

        docker buildx create --use
        docker login ghcr.io -u "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"

        time docker buildx build . --push \
            --file worker.Dockerfile \
            --progress plain \
            --platform linux/amd64,linux/arm64 \
            --tag "ghcr.io/subtrace/worker:${version}"
